export const AWS_S3_CONFIG = {
  STORAGE_PUBLIC: process.env.S3_STORAGE_PUBLIC,
  STORAGE_PRIVATE: process.env.S3_STORAGE_PRIVATE,
  ACCESS_KEY_ID: process.env.S3_ACCESS_KEY_ID,
  SECRET_ACCESS_KEY: process.env.S3_SECRET_ACCESS_KEY,
  REGION: process.env.S3_REGION,
  SIGNATURE_VERSION: process.env.S3_SIGNATURE_VERSION,
}
